#!/bin/bash -u

# Actualización de los paquetes
sudo pacman -Syu

# Instalación de programas via pacman
sudo pacman -S curl wget gcc git make meld r hunspell-es_es steam telegram-desktop texstudio vim yay
sudo pacman -S texlive

# Instalación de programas via yay
yay -S bitwarden discord_arch_electron google-chrome rstudio-desktop spotify visual-studio-code-bin

# Instalación de Albion Online
albion=albion-installer
curl https://live.albiononline.com/clients/20230814113608/albion-online-setup -o $albion
chmod +x $albion
./$albion
rm $albion

# Instalación de Beyond All Reason
bar=Beyond-All-Reason-1.2470.0.AppImage
wget https://github.com/beyond-all-reason/BYAR-Chobby/releases/download/v1.2470.0/Beyond-All-Reason-1.2470.0.AppImage
chmod +x $bar
mv $bar ~/Escritorio/$bar
~/Escritorio/$bar

# Instalación de drivers de nvidia
nvidia-inst --32 --conf
echo "Comprobar que el fichero de configuración es correcto https://wiki.archlinux.org/title/NVIDIA/Troubleshooting#Avoid_screen_tearing"
## nvidia-xconfig: X configuration file generated by nvidia-xconfig
## nvidia-xconfig:  version 535.86.05
#Section "Screen"
#    Identifier     "Screen0"
#    Device         "Device0"
#    Monitor        "Monitor0"
#    Option         "ForceFullCompositionPipeline" "on"
#    Option         "AllowIndirectGLXProtocol" "off"
#    Option         "TripleBuffer" "on"
#EndSection
yay -S envycontrol
echo "Si fuera necesario, se pueden instalar los paquetes vulkan-icd-loader lib32-vulkan-icd-loader nvidia-utils lib32-nvidia-utils lib32-opencl-nvidia"